language: go
go:
  - '1.15.5'
services:
  - docker

script:
  # https://docs.travis-ci.com/user/environment-variables/
  - 'bash -n build/build.sh'
  - '[ -z "$TRAVIS_TAG" ] && { bash build/build.sh build; ./gonelist --version; } || { bash build/build.sh release;bash build/build.sh docker; }'
before_install:
  - ls -l
after_script:
  - ls -l
  - ls -l release
deploy:
  provider: releases
  api_key: "${GONELIST_GITHUB_TOKEN}"
  file_glob: true
  file: release/*.tar.gz
  skip_cleanup: true
  on:
    tags: true